# Generated by Django 3.2 on 2021-05-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerFirstName', models.CharField(max_length=45)),
                ('ownerLastName', models.CharField(max_length=45)),
                ('ownerEmail', models.EmailField(max_length=254, unique=True)),
                ('ownerUsername', models.CharField(max_length=45)),
                ('shopName', models.CharField(max_length=50)),
                ('ownerPassword', models.CharField(max_length=45)),
                ('ownerUserCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ownerUserUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('userCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=45)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.CharField(max_length=45)),
                ('itemImg', models.CharField(max_length=255)),
                ('itemShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='crochetApp.owneruser')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=45)),
                ('assignedCat', models.ManyToManyField(related_name='categories', to='crochetApp.Products')),
            ],
        ),
    ]
