# Generated by Django 3.2 on 2021-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='itemName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='products',
            name='itemPrice',
            field=models.CharField(max_length=45),
        ),
    ]
