# Generated by Django 3.2 on 2021-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='itemImg',
            field=models.CharField(default='http://images.craftsnherbs.com/crochet/shawl.JPG', max_length=255),
            preserve_default=False,
        ),
    ]
