# Generated by Django 3.2 on 2021-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0004_products_itemimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerFirstName', models.CharField(max_length=45)),
                ('ownerLastName', models.CharField(max_length=45)),
                ('ownerEmail', models.EmailField(max_length=254, unique=True)),
                ('ownerUsername', models.CharField(max_length=45)),
                ('shopName', models.CharField(max_length=50)),
                ('ownerPassword', models.CharField(max_length=45)),
            ],
        ),
    ]
