# Generated by Django 3.2 on 2021-05-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0007_remove_products_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='crochetApp.owneruser'),
            preserve_default=False,
        ),
    ]
