# Generated by Django 3.2 on 2021-05-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochetApp', '0008_products_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='shop',
        ),
    ]
